spring:
  datasource:
    # url: jdbc:h2:tcp://localhost/~/data/auction;DB_CLOSE_DELAY=-1
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver

  flyway:
    enabled: false
    baseline-on-migrate: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  cache:
    type: NONE

  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: info
    org.hibernate:
      SQL: debug
      type: trace

jwt.secret: "12345678901234567890123456789012"
