name: CI for Auction backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci-job:
    runs-on: ubuntu-20.04
    services:
      redis: # Label used to access the service container
        image: redis # Docker Hub image
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build

      - name: build Docker
        run: |
          docker build -t eastshine/auction-backend:${GITHUB_SHA::7} .
          docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
          docker push eastshine/auction-backend:${GITHUB_SHA::7}
